
image:
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Release

for:

-
  matrix:
    only:
      - image: Visual Studio 2017

  install:
    - cinst --allow-empty-checksums smlnj
    - cinst meson
      
  build_script:
    - deploy\win32\build-32.bat

-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - cinst --allow-empty-checksums smlnj
      
  build_script:
    - deploy\win64\build-64.bat
  
