name: Linux CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install-packages
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libbz2-dev libfftw3-dev libfishsound1-dev libid3tag0-dev liblo-dev liblrdf0-dev libmad0-dev liboggz2-dev libopus-dev libopusfile-dev libpulse-dev libsamplerate-dev libsndfile-dev libsord-dev libxml2-utils portaudio19-dev qt5-default libqt5svg5-dev raptor2-utils git mercurial autoconf automake libtool mlton capnproto libcapnp-dev
    - name: install-meson
      run: |
        mkdir -p tmp/meson
        cd tmp/meson
        wget https://github.com/mesonbuild/meson/releases/download/0.56.0/meson-0.56.0.tar.gz
        tar xvf meson-0.56.0.tar.gz
        sudo ln -s $(pwd)/meson-0.56.0/meson.py /usr/bin/meson
    - name: install-ninja
      run: |
        mkdir -p tmp/ninja
        cd tmp/ninja
        wget https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip
        unzip ninja-linux.zip
        sudo ln -s $(pwd)/ninja /usr/bin/ninja
    - name: install-rubberband
      run: |
        mkdir -p tmp/rubberband
        cd tmp/rubberband
        wget https://breakfastquay.com/files/releases/rubberband-3.1.1.tar.bz2
        tar xvjf rubberband-3.1.1.tar.bz2
        cd rubberband-3.1.1
        meson build && ninja -C build && sudo ninja -C build install
    - name: repoint
      run: ./repoint install
    - name: configure
      run: meson build --buildtype release
    - name: make
      run: ninja -C build
    - name: test
      run: meson test -C build
