name: macOS CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: brew install polyml qt6 meson ninja capnp mercurial
    - name: repoint
      run: ./repoint install
    - name: configure
      run: PATH=$PATH:/usr/local/opt/qt6/bin meson setup build --buildtype release
    - name: make
      run: ninja -C build
    - name: test
      run: meson test -C build
    - name: deploy-app
      run: |
        QTDIR=/usr/local/opt/qt6 ./deploy/macos/deploy.sh "Sonic Visualiser"
    - name: check
      run: |
        otool -L ./"Sonic Visualiser.app/Contents/MacOS/Sonic Visualiser"
        ./"Sonic Visualiser.app/Contents/MacOS/Sonic Visualiser" --version
